services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGUSER=${DB_USER}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  backend:
    build: ./backend
    restart: always
    container_name: web_backend
    ports:
      - '8000:8000'
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    build: ./frontend
    restart: always
    container_name: web_frontend
    ports:
      - '5173:5173'
    command: npm run dev
    depends_on:
      - 'backend'

volumes:
  data: